### ISSUE TITLE
1_train_predictor --save_fig error

### ISSUE THREAD

**Issue by drpetershaw** [chickenbestlover/RNN-Time-series-Anomaly-Detection#21]
When i use:

!python /content/drive/My\ Drive/PlasmaSimAI/RNN/1_train_predictor.py --data ecg --filename chfdbchf15.pkl --save_fig

in Google colab the following error occurs:

> => Start training from scratch
-----------------------------------------------------------------------------------------
Namespace(augment=True, batch_size=64, bptt=50, clip=10, data='ecg', device='cuda', dropout=0.2, emsize=32, epochs=50, eval_batch_size=64, filename='chfdbchf15.pkl', log_interval=10, lr=0.0002, model='LSTM', nhid=32, nlayers=2, prediction_window_size=10, pretrained=False, res_connection=False, resume=False, save_fig=True, save_interval=10, seed=1111, teacher_forcing_ratio=0.7, tied=False, weight_decay=0.0001)
-----------------------------------------------------------------------------------------
| epoch   1 |    10/   31 batches | ms/batch 133.2217 | loss  2.27 
| epoch   1 |    20/   31 batches | ms/batch 117.8518 | loss  1.95 
| epoch   1 |    30/   31 batches | ms/batch 117.6507 | loss  2.02 
-----------------------------------------------------------------------------------------
| end of epoch   1 | time:  4.70s | valid loss 1.6075 | 
-----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/content/drive/My Drive/PlasmaSimAI/RNN/1_train_predictor.py", line 326, in <module>
    generate_output(args,epoch,model,gen_dataset,startPoint=1500)
  File "/content/drive/My Drive/PlasmaSimAI/RNN/1_train_predictor.py", line 141, in generate_output
    target= preprocess_data.reconstruct(gen_dataset.cpu().numpy(), TimeseriesData.mean, TimeseriesData.std)
  File "/content/drive/My Drive/PlasmaSimAI/RNN/preprocess_data.py", line 18, in reconstruct
    return seqData*std+mean
TypeError: mul(): argument 'other' (position 1) must be Tensor, not numpy.ndarray

When you remove --save_fig the code works as expected. Is this a bug or am i doing something wrong?

**Comment by chickenbestlover** [comment]
I agree with you. I tried to run this code in 1.0.0 with the --save_fig option and the same error occurred.

**Comment by chickenbestlover** [comment]
It seems that the error occurred because multiplication between Numpy array and Pytorch tensor is deprecated in Pytorch 1.0.0

**Comment by immanuvelprathap** [comment]
def generate_output(args,epoch, model, gen_dataset, disp_uncertainty=True,startPoint=500, endPoint=3500):
    if args.save_fig:
        # Turn on evaluation mode which disables dropout.
        model.eval()
        hidden = model.init_hidden(1)
        outSeq = []
        upperlim95 = []
        lowerlim95 = []
        with torch.no_grad():
            for i in range(endPoint):
                if i>=startPoint:
                    if disp_uncertainty and epoch > 40:
                        outs = []
                        model.train()
                        for i in range(20):
                            out_, hidden_ = model.forward(out+0.01*Variable(torch.randn(out.size())).cuda(),hidden,noise=True)
                            outs.append(out_)
                        model.eval()
                        outs = torch.cat(outs,dim=0)
                        out_mean = torch.mean(outs,dim=0) # [bsz * feature_dim]
                        out_std = torch.std(outs,dim=0) # [bsz * feature_dim]
                        upperlim95.append(out_mean + 2.58*out_std/np.sqrt(20))
                        lowerlim95.append(out_mean - 2.58*out_std/np.sqrt(20))

                    out, hidden = model.forward(out, hidden)

                    #print(out_mean,out)

                else:
                    out, hidden = model.forward(gen_dataset[i].unsqueeze(0), hidden)
                outSeq.append(out.data.cpu()[0][0].unsqueeze(0))


        outSeq = torch.cat(outSeq,dim=0) # [seqLength * feature_dim]

        target= preprocess_data.reconstruct(gen_dataset.cpu(), TimeseriesData.mean, TimeseriesData.std)
        outSeq = preprocess_data.reconstruct(outSeq, TimeseriesData.mean, TimeseriesData.std)
        if epoch>40:
            upperlim95 = torch.cat(upperlim95, dim=0)
            lowerlim95 = torch.cat(lowerlim95, dim=0)
            upperlim95 = preprocess_data.reconstruct(upperlim95.data.cpu().numpy(),TimeseriesData.mean,TimeseriesData.std)
            lowerlim95 = preprocess_data.reconstruct(lowerlim95.data.cpu().numpy(),TimeseriesData.mean,TimeseriesData.std)

        plt.figure(figsize=(15,5))
        for i in range(target.size(-1)):
            plt.plot(target[:,:,i].numpy(), label='Target'+str(i),
                     color='black', marker='.', linestyle='--', markersize=1, linewidth=0.5)
            plt.plot(range(startPoint), outSeq[:startPoint,i].numpy(), label='1-step predictions for target'+str(i),
                     color='green', marker='.', linestyle='--', markersize=1.5, linewidth=1)
            if epoch>40:
                plt.plot(range(startPoint, endPoint), upperlim95[:,i].numpy(), label='upperlim'+str(i),
                         color='skyblue', marker='.', linestyle='--', markersize=1.5, linewidth=1)
                plt.plot(range(startPoint, endPoint), lowerlim95[:,i].numpy(), label='lowerlim'+str(i),
                         color='skyblue', marker='.', linestyle='--', markersize=1.5, linewidth=1)
            plt.plot(range(startPoint, endPoint), outSeq[startPoint:,i].numpy(), label='Recursive predictions for target'+str(i),
                     color='blue', marker='.', linestyle='--', markersize=1.5, linewidth=1)

        plt.xlim([startPoint-500, endPoint])
        plt.xlabel('Index',fontsize=15)
        plt.ylabel('Value',fontsize=15)
        plt.title('Time-series Prediction on ' + args.data + ' Dataset', fontsize=18, fontweight='bold')
        plt.legend()
        plt.tight_layout()
        plt.text(startPoint-500+10, target.min(), 'Epoch: '+str(epoch),fontsize=15)
#         save_dir = Path('result',args.data,args.filename).with_suffix('').joinpath('fig_prediction')
#         save_dir.mkdir(parents=True,exist_ok=True)
        save_dir = r'/Users/immanuvelprathaps/Desktop/RNN-Time-series-Anomaly-Detection-master/result/ecg/chfdb_chf13_45590 fig_prediction fig_epoch'+ str(epoch)+ '.png'
#         plt.savefig(save_dir.joinpath('fig_epoch'+str(epoch)).with_suffix('.png'))
        plt.savefig(save_dir)
        plt.show()
        plt.close()
        
        return outSeq

    else:
        `[pass](url)`

### Namespace(augment=True, batch_size=64, bptt=50, clip=10, data='ecg', device='cpu', dropout=0.2, emsize=32, epochs=3500, eval_batch_size=64, filename='chfdb_chf13_45590.pkl', log_interval=10, lr=0.0002, model='LSTM', nhid=32, nlayers=2, prediction_window_size=10, pretrained=False, res_connection=False, resume=False, save_fig=False, save_interval=10, seed=1111, teacher_forcing_ratio=0.7, tied=False, weight_decay=0.0001)

save_fig=False, Anyone Know how to fix this? I'm using a Mac OS Monterey 12.1. @chickenbestlover 

Also, you have set parameters : startPoint=500, endPoint=3500 within the generate_output function, does this mean the png files start saving only after the 500 startPoint ? @chickenbestlover
