### ISSUE TITLE
TypeError: invalid file: WindowsPath('save/ecg/checkpoint/chfdb_chf13_45590.pth')

### ISSUE THREAD

**Issue by yunzhonghe2017** [chickenbestlover/RNN-Time-series-Anomaly-Detection#6]
=> saving checkpoint ..
Traceback (most recent call last):
  File "train_predictor.py", line 338, in <module>
    model.save_checkpoint(model_dictionary, is_best)
  File "C:\Users\Dell\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.5\model\model.py", line 103, in save_checkpoint
    torch.save(state, checkpoint)
  File "C:\Users\Dell\AppData\Roaming\Python\Python35\site-packages\torch\serialization.py", line 209, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "C:\Users\Dell\AppData\Roaming\Python\Python35\site-packages\torch\serialization.py", line 132, in _with_file_like
    f = open(f, mode)
TypeError: invalid file: WindowsPath('save/ecg/checkpoint/chfdb_chf13_45590.pth')

C:\Users\Dell\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.5>

**Comment by chickenbestlover** [comment]
The source code is tested on Ubuntu 16.04. You may have to change a few lines to run the source code in Windows.

**Comment by yunzhonghe2017** [comment]
Ok. Thanks.

**Comment by yunzhonghe2017** [comment]
I have tried. But, I don't know how to change it. Can you help me? @chickenbestlover

**Comment by mangoocmt** [comment]
Have you find the solution?

**Comment by mangoocmt** [comment]
@chickenbestlover What issues should be noted when to run the source code on Windows?

**Comment by chickenbestlover** [comment]
@yunzhonghe2017 Can you share the solution you found? Thank you!

**Comment by yunzhonghe2017** [comment]
i changed the savedir in train_predictor.py and model.py as follow:
![default](https://user-images.githubusercontent.com/34879553/48050675-79a9e700-e1dd-11e8-8b33-cbaff4eb0f22.JPG)
![1](https://user-images.githubusercontent.com/34879553/48050676-79a9e700-e1dd-11e8-9c61-e5066bf27887.JPG)
@mangoocmt

**Comment by Shenlihua85** [comment]
@yunzhonghe2017  I can't see the content you shared. Can you share the solution by sending an email to this mailbox : sacslh@126.com? Thank you very much!

**Comment by immanuvelprathap** [comment]
def generate_output(args,epoch, model, gen_dataset, disp_uncertainty=True,startPoint=500, endPoint=3500):
    if args.save_fig:
        # Turn on evaluation mode which disables dropout.
        model.eval()
        hidden = model.init_hidden(1)
        outSeq = []
        upperlim95 = []
        lowerlim95 = []
        with torch.no_grad():
            for i in range(endPoint):
                if i>=startPoint:
                    if disp_uncertainty and epoch > 40:
                        outs = []
                        model.train()
                        for i in range(20):
                            out_, hidden_ = model.forward(out+0.01*Variable(torch.randn(out.size())).cuda(),hidden,noise=True)
                            outs.append(out_)
                        model.eval()
                        outs = torch.cat(outs,dim=0)
                        out_mean = torch.mean(outs,dim=0) # [bsz * feature_dim]
                        out_std = torch.std(outs,dim=0) # [bsz * feature_dim]
                        upperlim95.append(out_mean + 2.58*out_std/np.sqrt(20))
                        lowerlim95.append(out_mean - 2.58*out_std/np.sqrt(20))

                    out, hidden = model.forward(out, hidden)

                    #print(out_mean,out)

                else:
                    out, hidden = model.forward(gen_dataset[i].unsqueeze(0), hidden)
                outSeq.append(out.data.cpu()[0][0].unsqueeze(0))


        outSeq = torch.cat(outSeq,dim=0) # [seqLength * feature_dim]

        target= preprocess_data.reconstruct(gen_dataset.cpu(), TimeseriesData.mean, TimeseriesData.std)
        outSeq = preprocess_data.reconstruct(outSeq, TimeseriesData.mean, TimeseriesData.std)
        if epoch>40:
            upperlim95 = torch.cat(upperlim95, dim=0)
            lowerlim95 = torch.cat(lowerlim95, dim=0)
            upperlim95 = preprocess_data.reconstruct(upperlim95.data.cpu().numpy(),TimeseriesData.mean,TimeseriesData.std)
            lowerlim95 = preprocess_data.reconstruct(lowerlim95.data.cpu().numpy(),TimeseriesData.mean,TimeseriesData.std)

        plt.figure(figsize=(15,5))
        for i in range(target.size(-1)):
            plt.plot(target[:,:,i].numpy(), label='Target'+str(i),
                     color='black', marker='.', linestyle='--', markersize=1, linewidth=0.5)
            plt.plot(range(startPoint), outSeq[:startPoint,i].numpy(), label='1-step predictions for target'+str(i),
                     color='green', marker='.', linestyle='--', markersize=1.5, linewidth=1)
            if epoch>40:
                plt.plot(range(startPoint, endPoint), upperlim95[:,i].numpy(), label='upperlim'+str(i),
                         color='skyblue', marker='.', linestyle='--', markersize=1.5, linewidth=1)
                plt.plot(range(startPoint, endPoint), lowerlim95[:,i].numpy(), label='lowerlim'+str(i),
                         color='skyblue', marker='.', linestyle='--', markersize=1.5, linewidth=1)
            plt.plot(range(startPoint, endPoint), outSeq[startPoint:,i].numpy(), label='Recursive predictions for target'+str(i),
                     color='blue', marker='.', linestyle='--', markersize=1.5, linewidth=1)

        plt.xlim([startPoint-500, endPoint])
        plt.xlabel('Index',fontsize=15)
        plt.ylabel('Value',fontsize=15)
        plt.title('Time-series Prediction on ' + args.data + ' Dataset', fontsize=18, fontweight='bold')
        plt.legend()
        plt.tight_layout()
        plt.text(startPoint-500+10, target.min(), 'Epoch: '+str(epoch),fontsize=15)
#         save_dir = Path('result',args.data,args.filename).with_suffix('').joinpath('fig_prediction')
#         save_dir.mkdir(parents=True,exist_ok=True)
        save_dir = r'/Users/immanuvelprathaps/Desktop/RNN-Time-series-Anomaly-Detection-master/result/ecg/chfdb_chf13_45590 fig_prediction fig_epoch'+ str(epoch)+ '.png'
#         plt.savefig(save_dir.joinpath('fig_epoch'+str(epoch)).with_suffix('.png'))
        plt.savefig(save_dir)
        plt.show()
        plt.close()
        
        return outSeq

    else:
        `[pass](url)`

### Namespace(augment=True, batch_size=64, bptt=50, clip=10, data='ecg', device='cpu', dropout=0.2, emsize=32, epochs=3500, eval_batch_size=64, filename='chfdb_chf13_45590.pkl', log_interval=10, lr=0.0002, model='LSTM', nhid=32, nlayers=2, prediction_window_size=10, pretrained=False, res_connection=False, resume=False, save_fig=False, save_interval=10, seed=1111, teacher_forcing_ratio=0.7, tied=False, weight_decay=0.0001)

```
Question1? save_fig=False, Anyone Know how to fix this? I'm using a Mac OS Monterey 12.1. @chickenbestlover @yunzhonghe2017  

Question2? Also, you have set parameters : startPoint=500, endPoint=3500 within the generate_output function, does this mean the png files start saving only after the 500 startPoint ? @chickenbestlover  @yunzhonghe2017 
```
